[build]
  command = "npm install && npm run build"
  publish = "dist/movie-ticket-host/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 # Redirige todas las rutas a index.html para SPA (Single Page Application)